load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    urls = ["https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip"],
    strip_prefix = "googletest-release-1.11.0",
    sha256 = "353571c2440176ded91c2de6d6cd88ddd41401d14692ec1f99e35d013feda55a"
)
http_archive(
    name = "json",
    strip_prefix = "json-3.10.5",
    urls = ["https://github.com/nlohmann/json/archive/refs/tags/v3.10.5.tar.gz"],
    sha256 = "5daca6ca216495edf89d167f808d1d03c4a4d929cef7da5e10f135ae1540c7e4",
)