
cc_library(
    name = "class",
    srcs = ["List.cpp",
            "double_linked_list.cpp"
            ],
    hdrs = ["List.hpp"
            "double_linked_list.hpp"
    ],
    visibility = ["//visibility:public"]
)
