
cc_test(
    name = "tests",
    srcs = ["tests.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/task-2:task-2",
        "//src/task-3:task-3",
        "//src/task-4:task-4",
        "//src/task-5:task-5",
        "//src/task-6:task-6",
    ]
)
