
cc_library(
    name = "class",
    srcs = ["Character.cpp",
            "magicCharacter.cpp"],
    hdrs = ["Character.hpp",
            "magicCharacter.hpp"],
    visibility = ["//visibility:public"]
)
